include:
  - services/adguardhome.yaml
  - services/bazarr.yaml
  - services/overseerr.yaml
  - services/prowlarr.yaml
  - services/radarr.yaml
  - services/sabnzbd.yaml
  - services/sonarr.yaml
  - services/traefik.yaml
  - services/whoami.yaml
  - services/watchtower.yaml

networks:
  sabnzbd:
    name: sabnzbd
  traefik:
    name: traefik
  overseerr:
    name: overseerr
  bazarr:
    name: bazarr

secrets:
  cloudflare-api-key:
    file: $CONFIG_PATH/secrets/cloudflare-selfhost-stack-letsencrypt-trtr-dot-co.txt
  duplicati-secrets-file:
    file: $CONFIG_PATH/secrets/duplicati-secrets-file.json
