networks:
  download-clients:
    name: download-clients
  traefik:
    name: traefik

services:
  #
  # Prowlarr - index aggregator
  #
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=002
    volumes:
      - $CONFIG_PATH/prowlarr:/config:rw
    labels:
      - autoheal=true
    healthcheck:
      test: curl -fSs http://127.0.0.1:9696 > /dev/null || exit 1
      start_period: 20s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped

  #
  # Radarr - Movies Search
  #
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    # ports:
    #   - 7878:7878
    environment:
      - UMASK_SET=22
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_PATH/radarr:/config
      - $DATA_PATH:/data
    networks:
      - download-clients
      - traefik
    labels:
      - autoheal=true
      - "traefik.http.routers.radarr.rule=Host(`radarr.trtr.co`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      # - "traefik.docker.network=traefik"
    healthcheck:
      test: curl -fSs http://127.0.0.1:7878 > /dev/null || exit 1
      start_period: 20s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    entrypoint:
      - /init
    depends_on:
      sabnzbd:
        condition: service_healthy

  #
  # Sonarr - Show Search
  #
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - UMASK_SET=22
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_PATH/sonarr:/config
      - $DATA_PATH:/data
    networks:
      - download-clients
    labels:
      - autoheal=true
    healthcheck:
      test: curl -fSs http://127.0.0.1:8989 || exit 1
      start_period: 90s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: "unless-stopped"
    entrypoint:
      - /init
    depends_on:
      sabnzbd:
        condition: service_healthy

  #
  # Bazarr - subtitles search
  #
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    ports:
      - 6767:6767
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022 #optional
    volumes:
      - $CONFIG_PATH/bazarr:/config
      - $DATA_PATH:/data
    labels:
      - autoheal=true
    healthcheck:
      test: curl -fSs http://127.0.0.1:6767 > /dev/null || exit 1
      start_period: 60s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    # mem_limit: 300M
    # mem_reservation: 250M

  #
  # Sabnzbd - Usenet downloader
  #
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_PATH/sabnzbd:/config
      - $DATA_PATH:/data
    networks:
      - download-clients
    labels:
      - autoheal=true
    healthcheck:
      test: curl -fSs 127.0.0.1:8080 > /dev/null || exit 1
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    # network_mode: "host"
    ports:
      # Plain DNS
      - "53:53/tcp"
      - "53:53/udp"
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - "81:81/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      # DNS-over-TLS
      - "853:853/tcp"
      # DNS-over-QUIC
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      # DNSCrypt
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - $CONFIG_PATH/adguardhome/config:/opt/adguardhome/conf # app configuration
      - $CONFIG_PATH/adguardhome/work:/opt/adguardhome/work # app working directory

  traefik:
    container_name: traefik
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    networks:
      - traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=traefik"

  whoami:
    container_name: whoami
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - download-clients
      - traefik
    labels:
      - "traefik.http.routers.foobar.rule=Host(`whoami.trtr.co`)"
