#
# AdGuard Home - DNS server/filtering
#

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    ports:
      # Plain DNS
      - "53:53/tcp"
      - "53:53/udp"
      # DNS-over-TLS
      - "853:853/tcp"
      # DNS-over-QUIC
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      # DNSCrypt
      - "5443:5443/tcp"
      - "5443:5443/udp"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.adguardhome.entrypoints=websecure"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.trtr.co`)"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=81"
    volumes:
      - $CONFIG_PATH/adguardhome/config:/opt/adguardhome/conf # app configuration
      - $CONFIG_PATH/adguardhome/work:/opt/adguardhome/work # app working directory

  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - CONFIGFILE=/config/adguardhome-sync.yaml
    volumes:
      - $CONFIG_PATH/adguardhome-sync:/config
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.adguardhomesync.entrypoints=websecure"
      - "traefik.http.routers.adguardhomesync.rule=Host(`adguard-sync.trtr.co`)"
    restart: unless-stopped
