services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      # - PLAYWRIGHT_DRIVER_URL= #optional
    volumes:
      - changedetection-data:/config
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.changedetection.entrypoints=websecure"
      - "traefik.http.routers.changedetection.rule=Host(`changedetection.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

volumes:
  changedetection-data:
