#
# Cloudflare Tunnel
#
services:
  cloudflared:
    container_name: cloudflare-tunnel
    build:
      dockerfile: Dockerfile.cloudflared
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    networks:
      - cloudflare-tunnel
    restart: unless-stopped
    secrets:
      - cloudflare-tunnel-token

secrets:
  cloudflare-tunnel-token:
    file: $CONFIG_PATH/secrets/cloudflare-tunnel-token.txt
