services:
  docker-exporter:
    container_name: docker-exporter
    image: ghcr.io/davidborzek/docker-exporter:latest
    user: root
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dockerexporter.entrypoints=websecure"
      - "traefik.http.routers.dockerexporter.rule=Host(`docker-exporter.trtr.co`)"
      - "traefik.http.services.dockerexporter.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
