#
# Duplicati - Backs up $CONFIG_PATH to windows pc
#
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
      - "DUPLICATI__SECRET_PROVIDER=file:///run/secrets/duplicati-secrets-file"
      - "DUPLICATI__WEBSERVICE_PASSWORD=$$ui-password"
      - "SETTINGS_ENCRYPTION_KEY=$$settings-key"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.duplicati.entrypoints=websecure"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - $CONFIG_PATH/duplicati/config:/config
      - $CONFIG_PATH:/source
    restart: unless-stopped
    secrets:
      - duplicati-secrets-file
