#
# Everyman movie listings
#
services:
  everyman:
    container_name: everyman
    image: ghcr.io/joshhunt/everyman-cinema-listings:release
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.everyman.entrypoints=websecure"
      - "traefik.http.routers.everyman.rule=Host(`everyman.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
