services:
  iperf-collector:
    container_name: iperf-collector
    image: ghcr.io/markormesher/iperf-prometheus-collector:latest
    restart: unless-stopped
    environment:
      - TARGET_LIST=192.168.1.102,ping.online.net,speedtest.lon12.uk.leaseweb.net
      - TEST_INTERVAL_MS=60000 # 60 seconds
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.iperf-collector.entrypoints=websecure"
      - "traefik.http.routers.iperf-collector.rule=Host(`iperf-collector.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.iperf-collector.loadbalancer.server.port=9030"
    networks:
      - traefik
