#
# Radarr - Movies
#

services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=22
    volumes:
      - radarr-config:/config
      - type: bind
        source: $DATA_PATH
        target: /data
    networks:
      - sabnzbd
      - traefik
      - bazarr
      - overseerr
      - prowlarr
      - scraparr
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    healthcheck:
      test: curl -fSs http://127.0.0.1:7878/ping > /dev/null || exit 1
      start_period: 60s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    entrypoint:
      - /init
    depends_on:
      sabnzbd: { condition: service_healthy }
      prowlarr: { condition: service_healthy }

volumes:
  radarr-config:
