services:
  #
  # Sonarr - Show Search
  #
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=22
    volumes:
      - sonarr-config:/config
      - $DATA_PATH:/data
    networks:
      - sabnzbd
      - traefik
      - overseerr
      - bazarr
      - prowlarr
      - scraparr
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.trtr.co`)"
      - "com.centurylinklabs.watchtower.enable=true"
      - "docker-volume-backup.stop-during-backup=true"
    healthcheck:
      test: curl -fSs http://127.0.0.1:8989 || exit 1
      start_period: 90s
      timeout: 5s
      interval: 5s
      retries: 3
    restart: "unless-stopped"
    entrypoint:
      - /init
    depends_on:
      sabnzbd:
        condition: service_healthy

volumes:
  sonarr-config:
