services:
  traefik:
    container_name: traefik
    image: traefik:v3.2
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-api-key
    command:
      # - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"

      # API + Dashboard
      - "--api=true"

      # Logs + Metrics
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addServicesLabels=true"

      # HTTP server -redirect to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

      # HTTPS server - use wildcard cert
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.domains[0].main=*.trtr.co"
      - "--entrypoints.websecure.http.tls.certresolver=wildcard"

      # LetsEncrypt DNS config
      - "--certificatesresolvers.wildcard.acme.dnschallenge=true"
      - "--certificatesresolvers.wildcard.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.wildcard.acme.dnschallenge.resolvers=1.1.1.1:53"
      - "--certificatesresolvers.wildcard.acme.email=letsencrypt@trtr.co"
      - "--certificatesresolvers.wildcard.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesresolvers.wildcard.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

    labels:
      - "traefik.enable=true"

      # Traefik Dashboard Route
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.trtr.co`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=wildcard"

      # Prometheus Metrics Route
      - "traefik.http.routers.traefik-metrics.rule=Host(`traefik.trtr.co`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.traefik-metrics.entrypoints=websecure"
      - "traefik.http.routers.traefik-metrics.service=prometheus@internal"
      - "traefik.http.routers.traefik-metrics.tls.certresolver=wildcard"

    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_PATH/traefik/letsencrypt:/letsencrypt
    secrets:
      - cloudflare-api-key

secrets:
  cloudflare-api-key:
    file: $CONFIG_PATH/secrets/cloudflare-selfhost-stack-letsencrypt-trtr-dot-co.txt
