#
# Watchtower - updates docker containers
#

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG_PATH/watchtower/config.json:/config.json
    command: --interval 30 --label-enable
