#
# Watchtower - updates docker containers
#
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WATCHTOWER_HTTP_API_TOKEN=insecure-token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--interval=3600"
      - "--label-enable"
      - "--cleanup"
      - "--http-api-periodic-polls"
      - "--http-api-update"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.watchtower.entrypoints=websecure"
      - "traefik.http.routers.watchtower.rule=Host(`watchtower.trtr.co`)"
